select * from customer
--Q1. What is the total revenue generated by male vs. female customers?
select gender , sum(purchase_amount_usd) as total_revenue
from customer 
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount_usd
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount_usd > (
    SELECT AVG(purchase_amount_usd)
    FROM customer
);
--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased as product ,round(avg(review_rating::numeric),2) as average 
from customer 
group by item_purchased 
order by average desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type, round(AVG(purchase_amount_usd::numeric),2) AS avg_purchase
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select count(customer_id) as total_customers ,round(avg(purchase_amount_usd::numeric),2) as avg_spend , sum(purchase_amount_usd) as total_revenue,subscription_status
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
Round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end )/count(*) ,2) as discount_rate
from customer
group by item_purchased 
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
select 
    case
	when previous_purchases = 1 then 'New' 
	when purchase_frequency_days  between 2 and 10 then 'Returning' 
	else 'loyal' end as customer_segment,
	count(*) as no_of_customers 
	from customer 
	group by customer_segment;


--Q8. What are the top 3 most purchased products within each category?
SELECT category, item_purchased, product
FROM (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS product,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rn
    FROM customer
    GROUP BY category, item_purchased
) sub
WHERE rn <= 3;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer 
where previous_purchases >5
group by subscription_status


--Q10. What is the revenue contribution of each age group?

select age_group,sum(purchase_amount_usd) as total_revenue
from customer
group by age_group
order by total_revenue desc;